name: MyPy

on:
  pull_request:
    paths:
      - '**.py'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  mypy:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        pyversion: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.4
      with:
        fetch-depth: 0
        persist-credentials: false
        
    - name: Setup Python (faster than using Python container)
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.pyversion }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      
    - name: Add Poetry to PATH on Windows
      if: runner.os == 'Windows'
      run: $env:Path += ";$env:USERPROFILE\.poetry\bin"

    - name: Install Dependencies
      run: poetry install --no-interaction

    - name: Run MyPy
      run: make mypy
